// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlM5lR4pPc7xoe7MadpyQmfKJPm1kBj0w',
    appId: '1:843778808385:web:1d58eaf3ede404120cc4c0',
    messagingSenderId: '843778808385',
    projectId: 'weather-app-52a94',
    authDomain: 'weather-app-52a94.firebaseapp.com',
    storageBucket: 'weather-app-52a94.firebasestorage.app',
    measurementId: 'G-2PQGRX6S18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvg4vnP6XpyF8ty7o6AgMbBViPNNhZUWI',
    appId: '1:843778808385:android:3d4d6300fd10bde50cc4c0',
    messagingSenderId: '843778808385',
    projectId: 'weather-app-52a94',
    storageBucket: 'weather-app-52a94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3CrWCLFMDl43nHPkA1C3pKZw9QhEvOLk',
    appId: '1:843778808385:ios:c9038b1f3154d8e10cc4c0',
    messagingSenderId: '843778808385',
    projectId: 'weather-app-52a94',
    storageBucket: 'weather-app-52a94.firebasestorage.app',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3CrWCLFMDl43nHPkA1C3pKZw9QhEvOLk',
    appId: '1:843778808385:ios:c9038b1f3154d8e10cc4c0',
    messagingSenderId: '843778808385',
    projectId: 'weather-app-52a94',
    storageBucket: 'weather-app-52a94.firebasestorage.app',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlM5lR4pPc7xoe7MadpyQmfKJPm1kBj0w',
    appId: '1:843778808385:web:23c2abc3c98367870cc4c0',
    messagingSenderId: '843778808385',
    projectId: 'weather-app-52a94',
    authDomain: 'weather-app-52a94.firebaseapp.com',
    storageBucket: 'weather-app-52a94.firebasestorage.app',
    measurementId: 'G-7KGWYRQ33F',
  );
}
